import Sequelize from 'sequelize';
import { VISIBILITY } from '../config/constants';
export default function mediaFile(sequelizeAdapter) {
	const MediaFile = sequelizeAdapter.define(
		'mediaFile',
		{
			// ID generated by clients using shortid before the server assigns a uniqueId
			clientSideId: { type: Sequelize.STRING },
			minGroupRead: { type: Sequelize.INTEGER, defaultValue: 3 },
			minGroupModify: { type: Sequelize.INTEGER, defaultValue: 3 },
			minGroupDelete: { type: Sequelize.INTEGER, defaultValue: 3 },
			//viewPermission: { type: Sequelize.ENUM(VISIBILITY.PUBLIC, VISIBILITY.PRIVATE, VISIBILITY.RESTRICTED), defaultValue: VISIBILITY.PRIVATE },
			// The filename at the time of uploading. Can be changed as the file is stored using its id and file type: {id}.{fileType}
			fileName: { type: Sequelize.STRING, allowNull: true },
			title: { type: Sequelize.STRING },
			description: { type: Sequelize.TEXT },
			fileType: { type: Sequelize.STRING, allowNull: true },
			mimeType: { type: Sequelize.STRING, allowNull: true },
			size: { type: Sequelize.DECIMAL, allowNull: true },
			// purpose of the media file
			purpose: { type: Sequelize.ENUM('title', 'kitchen', 'bathroom', 'room', 'other', 'outside', 'location'), defaultValue: 'other', allowNull: true },
		},
		{
			// options
		}
	);
	MediaFile.associate = function(models) {
		models.Tenant.hasMany(models.MediaFile, { as: 'mediaFile', foreignKey: 'fk_tenant_id' });
		models.RealEstate.hasMany(models.MediaFile, { foreignKey: 'fk_realEstate_id' });
	};
	return MediaFile;
}
