version: "3"

services:
  proxy:
    image: nginx:1.15-alpine
    depends_on:
      - web
      - api
      - adminer
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../proxy/config2:/etc/nginx
      #- ../proxy/config2/certbot/conf:/etc/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
      # - ../proxy/config2/certbot/www:/var/www/certbot
      - ../proxy/config2/logs:/var/log/nginx
    networks:
      proxy:

networks:
  proxy:
    external: true
