version: "3"

services:
  reverse:
    hostname: reverseproxy
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config:/etc/nginx
      #- <path/to/your/certs>:/etc/ssl/private
    networks:
      proxy:

networks:
  proxy:
    external: true
