# Use root/example as user/password credentials
version: "3.8"

services:
  web-built:
    image: nginx:stable-alpine
    ports:
      - ${WEBAPP_PORT}:80
    volumes:
      - ../ui-vuetify/dist:/usr/share/nginx/html
      - ../ui-vuetify/nginx/nginx.conf:/etc/nginx/nginx.conf
    command: [nginx, "-g", "daemon off;"]
    environment:
      VUE_APP_API_URL: ${VUE_APP_API_URL}
      VUE_APP_THEME_COLOR: ${VUE_APP_THEME_COLOR}
    networks:
      proxy:

  web:
    image: node:13.6.0-alpine3.10
    restart: "no"
    volumes:
      - ../ui-vuetify:/usr/src/app
    working_dir: /usr/src/app
    command: "yarn serve --port 8080"
    environment:
      VUE_APP_API_URL: ${VUE_APP_API_URL}
      VUE_APP_THEME_COLOR: ${VUE_APP_THEME_COLOR}
    env_file:
      - ./.env-${ENV}
    ports:
      - ${WEBAPP_PORT}:8080
    networks:
      proxy:

  api:
    image: node:13.6.0-alpine3.10
    restart: "no"
    volumes:
      - ../api:/usr/src/app # map code
      - ../api/media:/usr/src/app/media

    working_dir: /usr/src/app
    command: yarn start
    env_file:
      - ./.env-${ENV}
    environment:
      API_SERVER_PORT: ${API_SERVER_PORT}
      API_MONGO_DB_PORT: ${API_MONGO_DB_PORT}
      API_MONGO_HOST: ${API_MONGO_HOST}
    ports:
      - ${API_SERVER_PUBLIC_PORT}:${API_SERVER_PORT}
    depends_on:
      - db
    networks:
      proxy:

  db:
    image: mariadb/server
    # !!! command is a must if using with mariaDb driver -- otherwise you'll have connection issues !!!
    #
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_INITDB_SKIP_TZINFO: "true"
    volumes:
      - ../db/mysql/data:/var/lib/mysql
      - ../db/mysql/db-setup/default:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306

    networks:
      - proxy

  adminer:
    image: adminer
    restart: always
    ports:
      - ${DB_ADMIN_PORT}:8080
    networks:
      - proxy

  mongo:
    image: mongo

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      MONGO_INITDB_ROOT_USERNAME: imonet
      MONGO_INITDB_ROOT_PASSWORD: imonet
      MONGO_INITDB_DATABASE: imonet
    ports:
      - $MONGO_DB_EXPOSED_PORT:27017
    volumes:
      - ../db/mongo/data:/var/lib/mongo
      - ../db/mongo/db-setup:/docker-entrypoint-initdb.d
    networks:
      - proxy

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - $MONGO_EXPRESS_UI_EXPOSED_PORT:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: imonet
      ME_CONFIG_MONGODB_ADMINPASSWORD: imonet
    networks:
      - proxy
networks:
  proxy:
volumes:
  api:
  mysql:
  data:
    driver: local
