#!/bin/bash
#GRANT ALL PRIVILEGES ON *.* TO '${DB_USER}'@'%';
mysql -uroot -p${MYSQL_PASSWORD}<<EOFMYSQL
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER}'@'%' WITH GRANT OPTION;

CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER}'@'localhost' WITH GRANT OPTION;

EOFMYSQL

flush privileges;

